#!/usr/bin/perl

$fn=shift;

print "#include \"$fn\"\n\n";

open IN, $fn;
while (<IN>) {
    if (/^JNIEXPORT ([a-z]+) JNICALL ([a-zA-Z0-9_]+)/) {
	$ret=$1; $fn=$2;
	$a=<IN>;
	if ($a=~/\((JNIEnv.*)\)/) {
	    $par=$1;
	    @p=split /,/,$par; $i=0; undef @pc;
	    foreach (@p) { $_.=" par$i"; push @pc, "par$i"; $i++; }
	    $parn=join ',',@p;
	    $parc=join ', ',@pc;
	    $rc = ($ret eq 'void')?'':'return ';
	    print "typedef $ret(Call_${fn}_t*)($par);\nCall_${fn}_t Call_$fn;\n";
	    print "JNIEXPORT $ret JNICALL $fn\n  ($parn) {\n    $rc Call_$fn($parc);\n  }\n\n";
	}
    }
}
