#!/bin/sh

PNAME=JGRlinux
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../../../org /tmp

rm -f /tmp/org/rosuda/${PNAME}/mkdist

cd /tmp/org/rosuda/${PNAME}

echo "Running autoconf ..."
rm -rf autom4te*
autoreconf
#autoheader
#autoconf
rm -rf autom4te*

echo "Compiling getsp ..."
if [ ! -e tools/getsp.class ]; then
    cd tools
    javac getsp.java
    cd ..
fi

echo "Removing CVS and backup stuff ..."
find . -name CVS | xargs rm -rf
find . -name \*~ | xargs rm -f

echo "Updating version ..."
VER=`awk -v ORS= '/JGR_VERSION / { print $2 }' ../JGR/JGR.java`
echo "$PNAME version ${VER}"

echo "Creating package ..."
cd ..
tar fcz ${PNAME}-${VER}.tar.gz ${PNAME}
cd ${SWD}
cp /tmp/org/rosuda/${PNAME}-${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}-${VER}.tar.gz
