#--- the following might work on Linux
# You should adapt the first two lines to match your setup

RHOME=/usr/local/lib/R
JAVAHOME=/usr/local/java
PLATFORM=amd64/server

JAVAINC=-I$(JAVAHOME)/include -I$(JAVAHOME)/include/linux
JNISO=.so
JNILD=-shared -L$(JAVAHOME)/jre/lib/$(PLATFORM) -ljvm
CPICF=-fPIC
JAVAB=$(JAVAHOME)/bin/java
JNIPREFIX=lib
