#--- the following might work on Linux
# You should adapt the first two lines to match your setup

RHOME=/usr/local/lib/R
JAVAHOME=/usr/lib/java

JAVAINC=-I$(JAVAHOME)/include -I$(JAVAHOME)/include/linux
JNISO=.so
JNILD=-shared -L$(JAVAHOME)/jre/lib/i386/client -ljvm
CPICF=-fPIC
JAVAB=$(JAVAHOME)/bin/java
JNIPREFIX=lib
