/*
 * JComboBoxExt.java
 *
 * Created on 18. August 2005, 16:15
 *
 */

package org.rosuda.JClaR;

//JGR - Java Gui for R, see http://www.rosuda.org/JGR/
//Copyright (C) 2003 - 2005 Markus Helbig
//--- for licensing information see LICENSE file in the original JGR distribution ---


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * JComboBoxExt - add JTextField in a JComboBox.
 *
 * @author Markus Helbig
 *
 * RoSuDa 2003 - 2005
 *
 */

public final class JComboBoxExt extends JComboBox {
    /**
     * FIXME: serialVersionUID field auto-generated by RefactorIT
     */
    static final long serialVersionUID = 200602271256L;
    
    private JTextField tf;
    
    private final class CBDocument extends PlainDocument {
        /**
         * FIXME: serialVersionUID field auto-generated by RefactorIT
         */
        static final long serialVersionUID = 200602271256L;
        public void insertString(final int offset, final String str, final AttributeSet a) throws BadLocationException {
            super.insertString(offset,str,a);
        }
    }
    
    JComboBoxExt(final String[] str) {
        super(str);
        if (getEditor() != null) {
            tf = (JTextField) getEditor().getEditorComponent();
            tf.addKeyListener(new KeyAdapter() {
                public final void keyPressed(final KeyEvent e) {
                }
                
                public final void keyReleased(final KeyEvent e) {
                }
            });
            if (tf != null) {
                tf.setDocument(new CBDocument());
            }
        }
    }
    
    /**
     * Set the combobox editable.
     */
    public void setEditable(final boolean b) {
        if (b && tf != null) {
            tf.requestFocus();
            tf.select(0,tf.getText().length());
        }
        super.setEditable(b);
    }
    
}