package org.rosuda.JClaR;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.ListIterator;
import javax.swing.JFrame;
import javax.swing.JPanel;


public abstract class SidePanel extends JPanel {
    /**
     * FIXME: serialVersionUID field auto-generated by RefactorIT
     */
    protected static final long serialVersionUID = 200602271310L;

    /** Autogenerated proxy constructor. */
    SidePanel() {
        super();
    }

    JFrame parent;    
    boolean noRecalc;
    NumberFormat numberFormat;
    
    private ArrayList<SimpleChangeListener> listeners = new ArrayList<SimpleChangeListener>();
    
    final void setParent(final JFrame parent){
        this.parent=parent;
    }
    
    final void fire(final int message){
        for(final ListIterator en = listeners.listIterator(); en.hasNext();) {
            ((SimpleChangeListener)en.next()).stateChanged(new SimpleChangeEvent(this,message));
        }
        
    }
    
    final void addSimpleChangeListener(final SimpleChangeListener scl){
        listeners.add(scl);
    }
    
    abstract boolean getAutoRecalc();
    
    static final int EVT_TRAIN = 0;
    static final int EVT_UPDATE_PLOT = 1;

}
