/*
 * SnapshotPanel.java
 *
 * Created on 27. Juli 2005, 14:40
 */

package org.rosuda.JClaR;

import java.awt.event.ActionListener;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.ImageIcon;

/**
 *
 * @author  tobias
 */
public final class SnapshotPanel extends javax.swing.JPanel {
    
    private SnapshotListModel slm;
    
    /** Creates new form SnapshotPanel */
    public SnapshotPanel() {
        initComponents();
        
        slm = new SnapshotListModel();
        lstSnapshots.setModel(slm);
    }
    
    public void addSnapshot(final SnapshotContainer snapC){
        slm.addSnapshot(snapC);
    }
    
    public SnapshotContainer getSelectedSnapshot(){
        final int index;
        if ((index=lstSnapshots.getSelectedIndex())!=-1) {
            return slm.getSnapshotAt(index);
        }
        
        else  {
            return null;
        }
        
    }
    
    public void  addRestoreActionListener(final ActionListener l){
        butRestore.addActionListener(l);
    }
    
    
    public final class SnapshotList extends javax.swing.JList {
        public String getToolTipText(final java.awt.event.MouseEvent event) {
            return slm.getSnapshotAt(locationToIndex(event.getPoint())).getToolTipText();
        }
    }
    
    public final class SnapshotListModel extends javax.swing.AbstractListModel {
        private Vector snapshots=new Vector();

        private Hashtable cache=new Hashtable();
        
        public void addSnapshot(final SnapshotContainer snapC){
            snapshots.add(0,snapC);
            fireContentsChanged(this, getSize()-2,getSize()-1);
        }
        
        public Object getElementAt(final int index){
            Object ret=null;
            if (lstSnapshots.isSelectedIndex(index)){
                if((ret=cache.get(snapshots.elementAt(index)))==null){
                    ret = new ImageIcon(SelectImageFilter.createSelectedImage(((SnapshotContainer)snapshots.elementAt(index)).getThumbnail().getImage()));
                    cache.put(snapshots.elementAt(index), ret);
                }
            } else{
                ret = ((SnapshotContainer)snapshots.elementAt(index)).getThumbnail();
            }
            return ret;
        }
        
        public int getSize(){
            if (snapshots!=null)  {
                return snapshots.size();
            }
            
            else  {
                return 0;
            }
            
        }
        
        public SnapshotContainer getSnapshotAt(final int index){
            return (SnapshotContainer)snapshots.elementAt(index);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        butRestore = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSnapshots = new SnapshotList();

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(135, 32767));
        setMinimumSize(new java.awt.Dimension(131, 57));
        setPreferredSize(new java.awt.Dimension(135, 10));
        butRestore.setText("Restore");
        jPanel1.add(butRestore);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        lstSnapshots.setMinimumSize(new java.awt.Dimension(120, 0));
        jScrollPane2.setViewportView(lstSnapshots);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butRestore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstSnapshots;
    // End of variables declaration//GEN-END:variables
    
}
