/*
 * SVMPreferencesPanel.java
 *
 * Created on 18. August 2005, 18:32
 */

package org.rosuda.JClaR;


/**
 *
 * @author  tobias
 */
public final class SVMPreferencesPanel extends javax.swing.JPanel {
    /**
     * FIXME: serialVersionUID field auto-generated by RefactorIT
     */
    static final long serialVersionUID = 200602271310L;
    
   
    
    /** Creates new form SVMPreferencesPanel */
    SVMPreferencesPanel() {
        initComponents();
        
   
    }
    
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 0));

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
